repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^dist/
      - id: end-of-file-fixer
        exclude: ^dist/
      - id: check-yaml
      - id: check-added-large-files
        exclude: ^dist/
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
        exclude: ^package-lock\.json$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        exclude: ^(dist/|.*\.md$)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.js$
        args: ['--fix']
        exclude: ^dist/
