name: Build dist

on:
  push:
    branches: [main]
    paths:
      - 'index.js'
      - 'lib/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build dist
        run: npm run build

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain dist)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Build dist with Node 20

          🤖 Automated build from workflow"
          git push
